##
# @file
#
# Travis CI script for the Brackets coding puzzle
#
# @author Emil Maskovsky
#
language: cpp
compiler:
- gcc
# - clang
script: make
# need to install the Boost libraries to the sandbox
before_script:
- sudo apt-get update -qq
- sudo apt-get install libboost-thread-dev libboost-system-dev
notifications:
email:
recipients: ankithbti007@gmail.com
on_success: change
on_failure: always